version: "3.8"

services:

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
      container_name: elasticsearch_springboot
      environment:
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - "discovery.type=single-node"
          - xpack.security.enabled=false
      ports:
          - "9200:9200"
      volumes:
#          - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
          - elasticsearch_data:/usr/share/elasticsearch/data
      networks:
          - elastic

    kibana:
      image: docker.elastic.co/kibana/kibana:8.9.0
      container_name: kibana_springboot
      ports:
          - "5601:5601"
      environment:
          ELASTICSEARCH_URL: http://elasticsearch:9200
          ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
          XPACK_SPACES_ENABLED: true
#          APPENDERS_ROLLING-FILE_TYPE: rolling-file
#          APPENDERS_ROLLING-FILE_FILENAME: /var/log/elasticsearch/kibana.log
#          APPENDERS_ROLLING-FILE_POLICY_TYPE: time-interval
#          APPENDERS_ROLLING-FILE_POLICY_INTERVAL: 300s
#          APPENDERS_ROLLING-FILE_POLICY_MODULATE: true
#          APPENDERS_ROLLING-FILE_STRATEGY_TYPE: numeric
#          APPENDERS_ROLLING-FILE_STRATEGY_PATTERN: -%i
#          APPENDERS_ROLLING-FILE_STRATEGY_MAX: 10
#          APPENDERS_ROLLING-FILE_LAYOUT_TYPE: pattern
      depends_on:
          - elasticsearch
      volumes:
          - type: volume
            source: logs
            target: /var/log/elasticsearch
          - kibana_data:/usr/share/kibana/data
      networks:
          - elastic

    logstash:
      image: docker.elastic.co/logstash/logstash:8.9.0
      container_name: logstash_springboot
      volumes:
        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
        - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      ports:
        - "5044:5044"
        - "5000:5000/tcp"
        - "5000:5000/udp"
        - "9600:9600"
      environment:
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        - elastic
      depends_on:
        - elasticsearch

networks:
  elastic:
    driver: bridge

volumes:
    elasticsearch_data:
        driver: local
    kibana_data:
        driver: local
    logs:
        driver: local
        
        